export const ADICIONA_PROJETO = 'ADICIONA_PROJETO';
export const ALTERA_PPROJETO = 'ALTERA_PPROJETO';
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO';
export const SET_PROJETOS = 'SET_PROJETOS';

export const NOTIFICAR = 'NOTIFICAR';
